name: elmridgedental
region: nyc

services:
  - name: web
    github:
      repo: jeffmuszynski/elmridgedental
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    source_dir: /
    run_command: npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: web
    - match:
        authority:
          exact: elmridgedental.com
        path:
          prefix: /
      redirect:
        authority: www.elmridgedental.com
        scheme: https
        redirect_code: 301
    - match:
        path:
          exact: /reviews
      redirect:
        uri: /patient-reviews
        redirect_code: 301
    - match:
        path:
          exact: /reviews/
      redirect:
        uri: /patient-reviews
        redirect_code: 301
    - match:
        path:
          exact: /before-and-after
      redirect:
        uri: /cosmetic-dentistry-killeen-tx
        redirect_code: 301
    - match:
        path:
          exact: /before-and-after/
      redirect:
        uri: /cosmetic-dentistry-killeen-tx
        redirect_code: 301
    - match:
        path:
          exact: /implant-bridges-killeen-tx
      redirect:
        uri: /implant-bridge-killeen-tx
        redirect_code: 301
    - match:
        path:
          exact: /implant-bridges-killeen-tx/
      redirect:
        uri: /implant-bridge-killeen-tx
        redirect_code: 301
    - match:
        path:
          exact: /patient-reviews/
      redirect:
        uri: /patient-reviews
        redirect_code: 301
    - match:
        path:
          prefix: /patient-reviews
      component:
        name: web
    - match:
        path:
          prefix: /
      component:
        name: web
